# Generated by Django 4.0.5 on 2022-06-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlering', '0003_esgscore_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgscore',
            name='name',
        ),
    ]
