# Generated by Django 4.0.5 on 2022-06-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlering', '0005_esgscore_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgscore',
            name='Name',
            field=models.CharField(max_length=500),
        ),
    ]
