# Generated by Django 4.0.5 on 2022-06-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlering', '0006_alter_esgscore_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esgscore',
            old_name='Name',
            new_name='name',
        ),
    ]
