# Generated by Django 4.0.5 on 2022-06-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlering', '0007_rename_name_esgscore_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esgscore',
            old_name='name',
            new_name='Name',
        ),
    ]
